sudo: false
language: go
install:
  - go get -u git.torproject.org/pluggable-transports/meek.git/meek-client
script:
  - ls -l $GOPATH/bin
  - cp $GOPATH/bin/meek-client $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: 4149b9da284e9452201acf739ad117dc1c94dd0f
  file: meek-client
  skip_cleanup: true
  on:
    tags: true
    
